import type { Metadata } from "next";
import { Poppins,Montserrat, Inter } from "next/font/google";
import "./globals.css";
import {NavBar} from "@/components";

const poppins = Poppins({
    weight:["400","600", "700"],
    variable: "--font-poppins",
    subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
      <NavBar/>
        {children}
      </body>
    </html>
  );
}
